### ISSUE TITLE
Feedback Postmortem i1

### ISSUE THREAD

**Issue by SandrineMartins** [joismar/SUAVE#18]
O que estava planejado: **OK**
O que foi feito: **OK**
O que não foi feito: **OK**
O que está planejado pra próxima iteração: **OK**
Lições aprendidas: **OK**
Atraso de 1 dia na entrega: **-2 pontos**

**Comment by holivra** [comment]
Sandrine, o Postmortem_1.md foi enviado 2 dias atrás, não entendi o motivo de possuir atraso na entrega (estava estipulado para a segunda-feira).

**Comment by Jcns** [comment]
Ah sim, foi um erro nosso (o github disse 2 dias atrás mas realmente foi de 00:06 do dia seguinte); Obrigado!
