### ISSUE TITLE
Correção TDD e BDD - Iteração 1

### ISSUE THREAD

**Issue by ps1312** [joismar/SUAVE#21]
## Testes BDD:

* Não encontrei os testes BDD de vocês

## Testes TDD:

* Não possui nenhum caminho triste -> Não possui, (-2)
* Todos os testes verdes -> Não, o teste do modelo de user não foi implementado

> Galera, removam os arquivos quando vocês não planejarem implementar o teste desse arquivo, o user_spec.rb não possui nenhuma implementação, isso pode confundir até vocês.
> Outro ponto, vocês colocaram os comportamentos que deveriam estar no BDD nos testes TDD. Um exemplo de teste que se encaixaria bem aqui era checar se, após o registro do usuário, o banco de dados possui uma linha com o username daquele usuário.

#### Nota TDD: 3
---
## nota final: 3

**Comment by Jcns** [comment]
Entendido. Apesar dele ter falado (em aula) que você pode inicialmente fazer apenas o caminho feliz e deixar o triste para depois. (como era a primeira criação de testes e ele nem deu tanto conteúdo, pensamos que apenas os felizes seria o suficiente, espero que fique mais claro o que de fato tem que ser entregue.) Obrigado!
