### ISSUE TITLE
Feedback Cadastrar histórias no gitHub

### ISSUE THREAD

**Issue by lsca** [joismar/SUAVE#56]
Fala pessoa, tudo certinho??

Pessoal, algumas issues ficaram sem descrição, por exemplo:
https://github.com/joismar/SUAVE/issues/48
https://github.com/joismar/SUAVE/issues/47
Houve uma penalização de -0,2 por isso.

10 -0,2 => 9,8
Nota final 9,8.

Qualquer duvida só responder a issue, caso contrario, só fechar ela.

**Comment by Jcns** [comment]
A gente não colocou a descrição pra ficar menos redundante do que já estaria. (No arquivo de histórias de usuários teria todas as descrições). Mas vamos corrigir isso. Obrigado!
