### ISSUE TITLE
Feedback Teste TDD e BDD - Iteração 2

### ISSUE THREAD

**Issue by mateusc42** [joismar/SUAVE#61]
Iae pessoal, vou dar o feedback dos testes TDD e BDD da iteração 2 de vocês. :)

## Testes TDD:
<ul>
  <li>Não possui nenhum caminho triste -> OK</li>
  <li>Todos os testes verdes -> Não, um falho(-1)</li>
</ul>

### Nota Final: 4
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Possui caminho feliz/triste -> OK</li>
  <li>Todos os testes verdes -> OK</li>
</ul>

### Nota Final: 5
---------------------------------------------------------------
> **Nota:** Adicionem a Label de FeedBack, não posso fazer isso porque não estou no projeto. Obrigado.

**Comment by Jcns** [comment]
Obrigado!
