### ISSUE TITLE
Feedback - Cadastrar histórias no gitHub - IT03

### ISSUE THREAD

**Issue by Lerissonf** [joismar/SUAVE#67]
## - Cadastrar histórias no gitHub

- ### _Uso de lable_ -> ok

- ### _Milestones_ -> ok
   

- ### _Descrição da issue_ -> ok
 	

- ### _1 Issue por participante_ -> ok

Obs.: atribuam a label FeedBack a essa issue, tudo certo, mas se tivessem uma forma de apontar a issue para cada hu do seu arquivo, seria legal só reforçando o que Serra disse na issue #56

**Comment by Jcns** [comment]
Vamos providenciar isso. Obrigado!
