### ISSUE TITLE
FeedBack - Postmortem - IT04

### ISSUE THREAD

**Issue by Lerissonf** [joismar/SUAVE#76]
# - **Postmortem**

- ### _Atraso na entrega do postmortem_ -> não (nota base 10.0)

- ### _Postmortem deve estar em markdown (.md)_ -> ok

- ### _Período da iteração_ -> - ok
    
- ### _O que estava planejado_ -> ok

- ### _O que foi feito_ -> ok
	
- ### _O que não foi feito_ -> ok

- ### _Planejado para próxima iteração_ ->ok

- ### _Lições aprendidas_ -> ok

## Nota final: 10.0

**Comment by Jcns** [comment]
Obrigado!
