### ISSUE TITLE
Feedback Cadastrar Histórias no GitHub e Testes TDD e BDD - Iteração 4

### ISSUE THREAD

**Issue by mateuscardosogs** [joismar/SUAVE#77]
Iae pessoal, vou passar o feedback do cadastro de histórias no gitHub e dos Testes TDD e BDD da iteração 4 de vocês. :)

## História dos Usuários:
<ul>
  <li>História bem descrita -> OK</li>
  <li>Uso de labels -> OK</li>
  <li>Milestones -> OK</li>
  <li>Descrição da issue -> OK</li>
  <li>Uma Issue por participante-> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

## Testes TDD:
<ul>
  <li>Não possui nenhum caminho triste -> OK</li>
  <li>Todos os testes verdes -> OK</li>
</ul>

#### Nota Final: 5
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Possui caminho feliz/triste -> OK</li>
  <li>Todos os testes verdes -> OK</li>
</ul>

#### Nota Final: 5
---------------------------------------------------------------

#### Nota Final: 10
---------------------------------------------------------------
> **Nota:** Adicionem a Label de FeedBack, não posso fazer isso porque não estou no projeto. Obrigado.

**Comment by Jcns** [comment]
Obrigado!
