### ISSUE TITLE
Correção da Iteração 0

### ISSUE THREAD

**Issue by mateusc42** [joismar/SUAVE#8]
Iae pessoal, vou dar o feedback da iteração 0 para vocês.

## Ata de reunião:
<ul>
  <li>Participantes da reunião -> OK</li>
  <li>Tópicos discutidos -> OK</li>
  <li>O que foi definido -> OK</li>
  <li>Formato Markdown -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

## História dos Usuários:
<ul>
  <li>Formato "como...eu gostaria... para.... -> OK</li>
  <li>História bem descrita -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

## Postmortem:
<ul>
  <li>Período -> OK</li>
  <li>O que estava planejado -> OK</li>
  <li>O que foi feito -> OK</li>
  <li>O que não foi feito -> OK</li>
  <li>O que está planejado pra próxima iteração -> OK</li>
  <li>Lições aprendidas -> OK</li>
  <li>Formato Markdown -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

## Preenchimento do GitHub:
<ul>
  <li>Nome do projeto -> OK</li>
  <li>Descrição do projeto -> OK</li>
  <li>Justificativa do projeto -> OK</li>
  <li>Especificação do papel dos membros -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

## Mockups e Storyboards:
<ul>
  <li>Mockups -> OK</li>
  <li>Storyboard -> OK</li>
</ul>

### Nota Final: 10

**Comment by Jcns** [comment]
Obrigado Mateus.
